### ISSUE TITLE
找不到对应的函数。这种怎么解决呢？

### ISSUE THREAD

**Issue by weaweawe01** [AzurLaneTools/ljd#3]
![image](https://user-images.githubusercontent.com/111571429/232499615-672532cc-f506-4d9b-9f6b-2174d82d5fee.png)

尝试了很多次。发现大多数都会出现 uv0 uv1..... 

测试环境：luajit-2.1.0-beta3

测试代码如下：

[1.zip](https://github.com/AzurLaneTools/ljd/files/11250723/1.zip)

**Comment by AutumnSun1996** [comment]
反编译本身是存在限制的，复杂情况下还是需要人工分析和处理，很多地方也得靠猜。
uvX是对upvalue的标记，具体得去看lua中的闭包和upvalue的相关内容。

**Comment by AutumnSun1996** [comment]
可以尝试的一些方案包括：手动修改和还原/直接调用字节码/优化ljd实现。
哪种方式更合适，得看你的具体使用场景和需求。
