### ISSUE TITLE
似乎无法还原blhx_2.0.0.10的luajit字节码?

### ISSUE THREAD

**Issue by flyqie** [AzurLaneTools/ljd#4]
大佬好, 感谢您开源该项目, 也看了您的博文.

测试了下blhx_2.0.0.10的lua文件, 似乎无法正常还原(AzurLane5.1-bcDec无报错但执行后output_dir内没有文件输出, AzurLaneTools/ljd直接还原也提示Warning: unknown opcode).

在jspzyhl/AzurLane5.1-bcDec也发了issue, 但作者似乎许久未登录github, 感觉有点悬.

小弟能力有限, 能麻烦您帮忙看下吗?

感谢.

LUA文件：
[lua_scripts.zip](https://github.com/AzurLaneTools/ljd/files/12909094/lua_scripts.zip)

libtolua.so(arm、x86)：
[apk_libs.zip](https://github.com/AzurLaneTools/ljd/files/12909095/apk_libs.zip)

apk文件：
https://pkg.biligame.com/games/blhx_2.0.0.10_45_20190516_115405_27d58.apk

**Comment by AutumnSun1996** [comment]
看了下你发的文件，应该是luajit字节码，做了opcode转换，所以会报‘unknown opcode’。
处理的思路是，找一个结构一致的简单文件，例如 tolua.lua, 然后对比一下可正常提取的文件，和异常文件的字节码。
当然，需要对 luajit 的字节码格式有一定的了解，这个需要去看文档。
如果按这个方式操作之后还有问题，可以邮件讨论。

字节码还原这部分不是本项目的处理范围，所以这个issue就先关掉了。
