### ISSUE TITLE
关于AzurLaneTools/AzurLaneLuaScripts自动更新失败的问题

### ISSUE THREAD

**Issue by flyqie** [AzurLaneTools/ljd#5]
非常抱歉在此项目下开issue，AzurLaneTools/AzurLaneLuaScripts似乎并没有启用issue。

目前经过本地测试发现scripts32仍然能通过与之前一致的方式进行解密，但似乎AzurLaneTools/AzurLaneLuaScripts在8.x及以后就无法正常自动更新了？

请问有计划修复吗，在github workflow看到您调用的是私有仓库来完成的自动化。

非常感谢！

**Comment by AutumnSun1996** [comment]
参考 https://github.com/AzurLaneTools/AzurLaneData/issues/11
AzurLaneLuaScripts 会在 AzurLaneData 修复后进行更新，具体日期还不确定。
