### ISSUE TITLE
luajit-decompiler-v2实验性支持?

### ISSUE THREAD

**Issue by flyqie** [AzurLaneTools/ljd#6]
您好，AzurLaneTools/AzurLaneLuaScripts似乎使用该仓库完成luajit反编译。

目前发现一个新的反编译器，本地测试效果确实比ljd好，请问有计划使用此反编译器另开一个AzurLaneTools/AzurLaneLuaScripts分支吗？

https://github.com/marsinator358/luajit-decompiler-v2

感谢！

**Comment by AutumnSun1996** [comment]
由于时间限制，目前暂时没有相关计划。
看了下 luajit-decompiler-v2, 是 C语言实现，没有提供python binding, 也没有 linux 下的编译结果, 因此接入的工作量估计会比较大.

如果有人愿意帮忙封装一个类似本仓库的 process_bytes 的python接口，我可以尝试更新一下。
